# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-13 01:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('umbrella_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='genre_id',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
    ]
